/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class registrationform extends javax.swing.JFrame {

   
     
    public registrationform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        title2 = new javax.swing.JLabel();
        usertxt2 = new javax.swing.JLabel();
        userfield2 = new javax.swing.JTextField();
        emailtxt = new javax.swing.JLabel();
        emailfield = new javax.swing.JTextField();
        phonenumtxt = new javax.swing.JLabel();
        phonenumfield = new javax.swing.JTextField();
        passtxt = new javax.swing.JLabel();
        passfield2 = new javax.swing.JPasswordField();
        cpasstxt = new javax.swing.JLabel();
        cpassfield = new javax.swing.JPasswordField();
        registerbtm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(860, 610));
        setPreferredSize(new java.awt.Dimension(860, 610));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title2.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        title2.setText("REGISTRATION FORM");
        jPanel2.add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 350, 60));

        usertxt2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        usertxt2.setText("USERNAME");
        jPanel2.add(usertxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 80, -1));

        userfield2.setBackground(new java.awt.Color(255, 204, 102));
        userfield2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        userfield2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        userfield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userfield2ActionPerformed(evt);
            }
        });
        jPanel2.add(userfield2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 280, 40));

        emailtxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailtxt.setText("EMAIL");
        jPanel2.add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 80, -1));

        emailfield.setBackground(new java.awt.Color(255, 204, 102));
        emailfield.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        emailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfieldActionPerformed(evt);
            }
        });
        jPanel2.add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 280, 40));

        phonenumtxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        phonenumtxt.setText("PHONE NUMBER");
        jPanel2.add(phonenumtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 120, -1));

        phonenumfield.setBackground(new java.awt.Color(255, 204, 102));
        phonenumfield.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        phonenumfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        phonenumfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenumfieldActionPerformed(evt);
            }
        });
        jPanel2.add(phonenumfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 280, 40));

        passtxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passtxt.setText("PASSWORD");
        jPanel2.add(passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 80, -1));

        passfield2.setBackground(new java.awt.Color(255, 204, 102));
        passfield2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passfield2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(passfield2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 280, 40));

        cpasstxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cpasstxt.setText("CONFIRM PASSWORD");
        jPanel2.add(cpasstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 160, -1));

        cpassfield.setBackground(new java.awt.Color(255, 204, 102));
        cpassfield.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cpassfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(cpassfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 280, 40));

        registerbtm.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        registerbtm.setText("REGISTER NOW");
        registerbtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbtmActionPerformed(evt);
            }
        });
        jPanel2.add(registerbtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 230, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 660));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -80, 960, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfieldActionPerformed

    private void phonenumfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenumfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenumfieldActionPerformed

    private void userfield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userfield2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userfield2ActionPerformed

    private void registerbtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerbtmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrationform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cpassfield;
    private javax.swing.JLabel cpasstxt;
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel emailtxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField passfield2;
    private javax.swing.JLabel passtxt;
    private javax.swing.JTextField phonenumfield;
    private javax.swing.JLabel phonenumtxt;
    private javax.swing.JButton registerbtm;
    private javax.swing.JLabel title2;
    private javax.swing.JTextField userfield2;
    private javax.swing.JLabel usertxt2;
    // End of variables declaration//GEN-END:variables
}
